src/Entity/Event.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 * @Vich\Uploadable()
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var File
     * @Vich\UploadableField(mapping="event_image", fileNameProperty=")
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name_event;

    /**
     * @ORM\Column(type="text")
     */
    private $short_description_event;

    /**
     * @ORM\Column(type="text")
     */
    private $long_description_event;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $ref_provider_event;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2)
     */
    private $purchase_price_event;

    /**
     * @ORM\Column(type="date")
     */
    private $start_date_event;

    /**
     * @ORM\Column(type="date")
     */
    private $end_date_event;

    /**
     * @ORM\Column(type="integer")
     */
    private $festival_place_event;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameEvent(): ?string
    {
        return $this->name_event;
    }

    public function setNameEvent(string $name_event): self
    {
        $this->name_event = $name_event;

        return $this;
    }

    public function getShortDescriptionEvent(): ?string
    {
        return $this->short_description_event;
    }

    public function setShortDescriptionEvent(string $short_description_event): self
    {
        $this->short_description_event = $short_description_event;

        return $this;
    }

    public function getLongDescriptionEvent(): ?string
    {
        return $this->long_description_event;
    }

    public function setLongDescriptionEvent(string $long_description_event): self
    {
        $this->long_description_event = htmlspecialchars($long_description_event);

        return $this;
    }

    public function getRefProviderEvent(): ?string
    {
        return $this->ref_provider_event;
    }

    public function setRefProviderEvent(string $ref_provider_event): self
    {
        $this->ref_provider_event = $ref_provider_event;

        return $this;
    }

    public function getPurchasePriceEvent(): ?float
    {
        return $this->purchase_price_event;
    }
    
    public function setPurchasePriceEvent(float $purchase_price_event): self
    {
        $this->purchase_price_event = $purchase_price_event;
        
        return $this;
    }

    public function getStartDateEvent(): ?\DateTimeInterface
    {
        return $this->start_date_event;
    }

    public function setStartDateEvent(\DateTimeInterface $start_date_event): self
    {
        $this->start_date_event = $start_date_event;

        return $this;
    }

    public function getEndDateEvent(): ?\DateTimeInterface
    {
        return $this->end_date_event;
    }

    public function setEndDateEvent(\DateTimeInterface $end_date_event): self
    {
        $this->end_date_event = $end_date_event;

        return $this;
    }

    public function getFestivalPlaceEvent(): ?int
    {
        return $this->festival_place_event;
    }

    public function setFestivalPlaceEvent(int $festival_place_event): self
    {
        $this->festival_place_event = $festival_place_event;

        return $this;
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name_event')
            ->add('short_description_event')
            ->add('long_description_event')
            ->add('ref_provider_event')
            ->add('purchase_price_event')
            ->add('start_date_event')
            ->add('end_date_event')
            ->add('festival_place_event');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Event::class
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/event")
 */
class EventController extends AbstractController
{
    public function __construct(EventRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/", name="event_index", methods={"GET"})
     */
    public function index(EventRepository $eventRepository): Response
    {
        return $this->render('event/index.html.twig', [
            'events' => $eventRepository->findAll()
        ]);
    }

    /**
     * @Route("/admin/new", name="event_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $event = new Event();
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('event_index');
        }

        return $this->render('event/new.html.twig', [
            'event' => $event,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}", name="event_show", methods={"GET"})
     */
    public function show(Event $event): Response
    {
        if (
            $this->container
                ->get('security.authorization_checker')
                ->isGranted('ROLE_SELLER')
        ) {
            return $this->render('event/show_admin.html.twig', [
                'event' => $event
            ]);
        } else {
            return $this->render('event/show_customer.html.twig', [
                'event' => $event
            ]);
        }
    }

    /**
     * @Route("/admin/{id}/edit", name="event_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Event $event): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()
                ->getManager()
                ->flush();

            return $this->redirectToRoute('event_index');
        }

        return $this->render('event/edit.html.twig', [
            'event' => $event,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/admin/{id}", name="event_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Event $event): Response
    {
        if (
            $this->isCsrfTokenValid(
                'delete' . $event->getId(),
                $request->request->get('_token')
            )
        ) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('event_index');
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('event_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/event/_form.html.twig
{{ form_start(form) }}
{{ form_rest(form) }}
<button class="btn btn-primary">{{button|default('Enregistrer')}}</button>
{{ form_end(form) }}

templates/event/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer l'évenement{% endblock %}

{% block body %}
    <h1 id="hautPage">Editer l'évenement</h1>

    {{ include('event/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('event_index') }}">Retour</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}

templates/event/event.html.twig
{% extends 'base.html.twig' %}

{% block title 'Evenement' %}

{% block body %}
	<div class="container">
		<h1>
			Nos événements

			<div class="row flex">
				{% for FicheArtiste in FichesArtiste %}
					<div class="col-3">
						<div class="card">
							<div class="card-body">
								<h5 class="card-title">
									<p class="card-text">{{ FicheArtiste.name_artiste }}</p>
									<div class="text-primary">{{ FicheArtiste.description_artiste }}</div>
								</div>
							</div>
						</div>
					{% endfor %}
				</h1>
			</div>
		{% endblock %}
{% extends 'footer.html.twig' %}

templates/event/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Gérer les évenement' %}

{% block body %}
			<div class="container">
	{% for message in app.flashes('success')%}
		<div class="alert alert-success">
			{{ message }}
		</div>
	{% endfor %}
	<div class="container-fluid mt-4">
		<h1 id="hautPage">Evenements disponible</h1>

			<!-- Page Content -->
				<div class="row">
				<div class="card-columns">
		{% for event in events %}
					<!-- Team Member 1 -->
					<div class="col">
						<div class="card border-0 shadow">
							<img src="{{ asset('assets/img/dj.jpg') }}" class="card-img-top" alt="...">
							<div class="card-body text-center">
								<h5 class="card-title mb-0">{{ event.nameEvent }}</h5>
								<div class="card-text text-black-50">{{ event.shortDescriptionEvent }}</div>
								<div class="card-text text-black-50">{{ event.longDescriptionEvent }}</div>
								{% if is_granted('ROLE_SELLER') %}
									<div class="card-text text-black-50">{{ event.refProviderEvent }}</div>
								{% endif %}
								<div class="card-text text-black-50">{{ event.purchasePriceEvent }}</div>

								<div class="btn-group" role="group" aria-label="Basic example">
									<button type="button" class="btn btn-pink btn-rounded">
										<a href="{{ path('event_show', {'id': event.id}) }}" class="text-muted">👁️</a>
									</button>
									{% if is_granted('ROLE_SELLER') %}
										<button type="button" class="btn btn-pink btn-rounded">
											<a href="{{ path('event_edit', {'id': event.id}) }}" class="text-muted">MODIF</a>
										</button>
									{% endif %}
									<button type="button" class="btn btn-pink btn-rounded">
										<a href="{{ path('cart_add', {'id':event.id} ) }}" class="text-muted"> 🛒</a>
									</button>
								</div>
						</div>
					</div>
				</div>
		{% endfor %}
				</div>
			</div>
				{% if is_granted('ROLE_SELLER') %}
		<div class="text-right">
			<a href="{{ path('event_new')}}" class="btn btn-light">
				Créer un nouvel évenement</a>
		</div>
	{% endif %}
	</tbody>
	</table>
{% include 'footer.html.twig' %}
{% endblock %}

templates/event/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Event{% endblock %}

{% block body %}
    <h1 id="hautPage">Nouvel événement</h1>

    {{ include('event/_form.html.twig') }}

    <a href="{{ path('event_index') }}">Retour</a>
{% endblock %}

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
    <h1>Event</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ event.id }}</td>
            </tr>
            <tr>
                <th>Name_event</th>
                <td>{{ event.nameEvent }}</td>
            </tr>
            <tr>
                <th>Short_description_event</th>
                <td>{{ event.shortDescriptionEvent }}</td>
            </tr>
            <tr>
                <th>Long_description_event</th>
                <td>{{ event.longDescriptionEvent }}</td>
            </tr>
            <tr>
                <th>Ref_provider_event</th>
                <td>{{ event.refProviderEvent }}</td>
            </tr>
            <tr>
                <th>Purchase_price_event</th>
                <td>{{ event.purchasePriceEvent }}</td>
            </tr>
            <tr>
                <th>Start_date_event</th>
                <td>{{ event.startDateEvent ? event.startDateEvent|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>End_date_event</th>
                <td>{{ event.endDateEvent ? event.endDateEvent|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Festival_place_event</th>
                <td>{{ event.festivalPlaceEvent }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('event_index') }}">back to list</a>

    <a href="{{ path('event_edit', {'id': event.id}) }}">edit</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}

templates/event/show_admin.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
    <h1 id="hautPage">Evénement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Nom</th>
                <td>{{ event.nameEvent }}</td>
            </tr>
            <tr>
                <th>Description courte</th>
                <td>{{ event.shortDescriptionEvent }}</td>
            </tr>
            <tr>
                <th>Description longue</th>
                <td>{{ event.longDescriptionEvent }}</td>
            </tr>
            <tr>
                <th>Référence fournisseur</th>
                <td>{{ event.refProviderEvent }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ event.purchasePriceEvent }}</td>
            </tr>
            <tr>
                <th>Début évenement</th>
                <td>{{ event.startDateEvent ? event.startDateEvent|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Début évenement</th>
                <td>{{ event.endDateEvent ? event.endDateEvent|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Nombre de place</th>
                <td>{{ event.festivalPlaceEvent }}</td>
            </tr>

        </tbody>
    <button type="button" class="btn btn-pink btn-rounded">
    <a href="{{ path('event_index') }}" class="text-muted">Retour</a>
    </button>
    <button type="button" class="btn btn-pink btn-roundedt">
    <a href="{{ path('event_edit', {'id': event.id})}}" class="text-muted">Modifier</a>
    </button>
    </table>
    {{ include('event/_delete_form.html.twig') }}
{% endblock %}

templates/event/show_customer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
    <image id="panier" class="featurette-image img-fluid mx-auto" alt="petite image" src="{{ asset('assets/img/admission.jpg') }}" data-holder-rendered="true">

    <table class="table">
        <tbody>
            <tr>
                <th></th>
                <td  id="nomConcert">{{ event.nameEvent }}</td>
            </tr>
            <tr>
                <th></th>
                <td>{{ event.shortDescriptionEvent }}</td>
            </tr>
            <tr>
                <th></th>
                <td>{{ event.longDescriptionEvent }}</td>
            </tr>
            <tr>
                <th></th>
                <td>{{ event.purchasePriceEvent }}</td>
            </tr>
            <tr>
                <th></th>
                <td>{{ event.startDateEvent ? event.startDateEvent|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th></th>
                <td>{{ event.endDateEvent ? event.endDateEvent|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th></th>
                <td>{{ event.festivalPlaceEvent }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-info" href="{{ path('event_index') }}">Retour</a>
{% endblock %}