src/Entity/Users.php
<?php

namespace App\Entity;

// use App\Entity\Users;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UsersRepository")
 * //permet d'avoir une valeur unique dans la BDD
 * @UniqueEntity("mail")
 */
class Users implements UserInterface,\Serializable
{
    const ROLES = [
        0 => 'ROLE_CUSTOMER',
        1 => 'ROLE_SELLER',
        2 => 'ROLE_MARKETING',
        3 => 'ROLE_MODERATOR',
        4 => 'ROLE_SUPER_ADMIN'
    ];
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\Regex(
     *     pattern="/^[A-Za-z ÁÀÂÄÃÅÉÈÊËÍÌÎÏÑÓÒÔÖÕÚÙÛÜÝÆÇáàâäãåéèêëíìîïñóòôöõúùûüýÿæç\'0-9,\.\-\_]{1,10}+$/",
     *     message="Veuillez saisir un nom valide"
     * )
     */
    private $name_users;

    /**
     * @ORM\Column(type="string", length=50)
     *  @Assert\Regex(
     *      pattern= "/^[A-Za-z ÁÀÂÄÃÅÉÈÊËÍÌÎÏÑÓÒÔÖÕÚÙÛÜÝÆÇáàâäãåéèêëíìîïñóòôöõúùûüýÿæç\'0-9,\.\-\_]{1,10}+$/",
     *      message="Veuillez saisir un prénom valide"
     * )
     */
    private $firstname_users;

    /**
     * @ORM\Column(type="string", length=10)
     * @Assert\Regex(
     *     pattern= "/([0-9]{2}){4}[0-9]{2}/",
     *     message="Veuillez saisir un numéro de téléphone valide"
     * )
     */
    private $phone_number_users;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\Regex(
     *      pattern= "/^[^\W][a-zA-Z0-9_]+(\.[a-zA-Z0-9_]+)*\@[a-zA-Z0-9_]+(\.[a-zA-Z0-9_]+)*\.[a-zA-Z]{2,4}$/",
     *      message="Veuillez saisir un mail valide"
     * )
     */
    private $mail;

    /**
      * @ORM\Column(type="string", length=60)
      * 
     */
    private $password_users;

    /**
     * @ORM\Column(type="integer")
     */
    private $role;

    
    private $retype_password_users;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameUsers(): ?string
    {
        return $this->name_users;
    }


    public function setNameUsers(string $name_users): self
    {
        $this->name_users = $name_users;

        return $this;
    }

    public function getSlug()
    {
        return (new Slugify())->slugify($this->name_users);
    }

    public function getFirstnameUsers(): ?string
    {
        return $this->firstname_users;
    }

    public function setFirstnameUsers(string $firstname_users): self
    {
        $this->firstname_users = $firstname_users;

        return $this;
    }

    public function getphoneNumberUsers(): ?string
    {
        return $this->phone_number_users;
    }

    public function setPhoneNumberUsers(string $phone_number_users): self
    {
        $this->phone_number_users = $phone_number_users;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getPasswordUsers(): ?string
    {
        return $this->password_users;
    }

    public function setPasswordUsers(string $password_users): self
    {
        $this->password_users = $password_users;

        return $this;
    }

    public function getRetypePasswordUsers(): ?string
    {
        return $this->retype_password_users;
    }

    public function setRetypePasswordUsers(string $retype_password_users): self
    {
        $this->retype_password_users = $retype_password_users;

        return $this;
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles() : array
    {
        $numero = $this->getRole();
        
        // 4
        if ($numero == array_search('ROLE_SUPER_ADMIN', self::ROLES))
        {
            $tableau = array(
                self::ROLES[0],
                self::ROLES[1],
                self::ROLES[2],
                self::ROLES[3],
                self::ROLES[4],
            );
            return $tableau;
        }

        // 0-3
        else {
            $mot = self::ROLES[$numero];            
            return array($mot);   
        }

    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        return null;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
    }

    /**
     * String representation of object
     * @link https://php.net/en/serializable.serialize.php
     * @return string the string representation of the object or null
     * @since 5.1.0
     */

     public function serialize()
     {
         return serialize([
             $this->id,
             $this->mail,
             $this->password_users
         ]);
     }

     /**
      * Constructs the object
      * @link https://php.net/manual/en/serializable.unserialize.php
      * @param string $serialized <p>
      * The string representation of the object.
      * </p>
      * @return void
      * @since 5.1.0
      */
     public function unserialize($serialized)
     {
        list (
            $this->id,
            $this->mail,
            $this->password_users
        ) = unserialize ($serialized, ['allowed_classes' => false]);
     }

     public function getUsername(): ?string
     {
         return $this->mail;
     }

     public function getPassword(): ?string
     {
         return $this->password_users;
     }

     public function getRole(): ?int
     {
         return $this->role;
     }

     public function setRole(int $role): self
     {
         $this->role = $role;

         return $this;
     }

}

src/Form/UsersType.php
<?php

namespace App\Form;

use App\Entity\Users;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotCompromisedPassword;

class UsersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name_users')
            ->add('firstname_users')
            ->add('phone_number_users')
            ->add('mail')
            ->add('password_users', PasswordType::class, [
                'mapped' => false,
                // protection entité password
                // test si mot de passe  n'est pas dans une base de données publiques
                'constraints' => [new NotCompromisedPassword()]
            ])
            ->add('retype_password_users', PasswordType::class)
            ->add('role');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Users::class,
            'translation_domain' => 'forms'
        ]);
    }
}

src/Controller/UsersController.php
<?php

namespace App\Controller;

use App\Entity\Users;
use App\Form\UsersType;
use App\Repository\UsersRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class UsersController extends AbstractController
{
    /**
     * @var UsersRepository
     */
    private $repository;

    public function __construct(UsersRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/concerts", name="users.index")
     * @return Response
     */
    public function index(): Response
    {
        $users = $this->repository->findAll();
        return $this->render('users/index.html.twig', [
            'current_menu' => 'users',
            'users' => $users
        ]);
    }

    /**
     * @Route("/new", name="user_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $users = new Users();
        $form = $this->createForm(UsersType::class, $users);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (
                $users->getPasswordUsers() == $users->getRetypePasswordUsers()
            ) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($users);
                $entityManager->flush();
                return $this->redirectToRoute('users.index');
            }
        }

        return $this->render('users/new.html.twig', [
            'users' => $users,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_edit", methods={"GET","POST"})
     */
    public function edit(
        Request $request,
        Users $users,
        UserPasswordEncoderInterface $passwordEncoder
    ): Response {
        $form = $this->createForm(UsersType::class, $users);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // code pour le mot de passe
            $users->setPasswordUsers(
                $passwordEncoder->encodePassword(
                    $users,
                    $form->get('password_users')->getData()
                )
            );
            $this->getDoctrine()
                ->getManager()
                ->flush();

            return $this->redirectToRoute('users.index');
        }

        return $this->render('users/edit.html.twig', [
            'users' => $users,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/users/{slug}-{id}", name="users.show"), requierements={"slug": [a-z0-9\-]*"})
     * @param Users $users
     * @return Response
     */
    //noms doivent correspondre à la route
    public function show(Users $users, string $slug): Response
    {
        if ($users->getSlug() !== $slug) {
            $this->redirectToRoute(
                'users/users.show',
                [
                    'id' => $users->getId(),
                    'slug' => $users->getSlug()
                ],
                301
            ); // code 301 : redirection permanente
        }
        return $this->render('users/show.html.twig', [
            'users' => $users,
            'current_menu' => 'users'
        ]);
    }

    /**
     * @Route("/{id}", name="user_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Users $users): Response
    {
        if (
            $this->isCsrfTokenValid(
                'delete' . $users->getId(),
                $request->request->get('_token')
            )
        ) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($users);
            $entityManager->flush();
            return $this->redirectToRoute('event_index');
        }

        return $this->redirectToRoute('users.index');
    }
}

templates/users/_form.html.twig
		{{ form_start(form) }}
		{{ form_rest(form) }}
        <button class="btn btn-primary">{{button|default('Enregistrer')}}</button>
		{{ form_end(form) }}

templates/users/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}

	<div class="container mt-4">
		<h2>Editer l'utilisateur:</h2>
	{{ include ('users/_form.html.twig', {form: form, button: 'Editer'}) }}
	{# {{ include('users/_form.html.twig', {'button_label': 'Editer'}) }} #}

	</div>

{% endblock %}

templates/users/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Gérer les utilisateurs' %}

{% block body %}
	<div class="container mt-4">
		<h1 id="hautPage">Gérer les utilisateurs</h1>

		<!-- condition pour afficher message addFlash -->
		{% for message in app.flashes('success')%}
			<div class="alert alert-success">
				{{ message }}
			</div>
		{% endfor %}
		<table class="table table-stripped">
			<thead>
				<tr>
					<th>Titre</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				{% for user in users %}
					<tr>
						<td>{{ user.nameUsers }}
							{{ user.firstnameUsers }}
						</td>
						<td>
							<a href="{{ path('user_edit', {id: user.id}) }}" class="btn btn-secondary">Editer</a>
							<form
								method="post" action="{{ path('admin.users.delete', {id: user.id})}}" style="display: inline-block" onsubmit="return confirm('Voulez-vous vraiment supprimer cette utilisateur?')">
								<!-- Champs caché de type hidden -->
								<input
								type="hidden" name="_method" value="DELETE">
								<!-- champ qui permet de sécurisé le formulaire de suppression avec un token -->
								<input type="hidden" name="_token" value="{{ csrf_token('user_delete')}}"/>
								<button class="btn btn-danger" type="submit">Supprimer</button>
							</form>
							<!-- champs caché -->
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		<div class="text-right">
			<a href="{{ path('user_new')}}" class="btn btn-primary">
				Créer un nouvel utilisateur</a>

		</div>

	{% endblock %}

templates/users/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}

	<div class="container mt-4">
		<h2 id="hautPage">Créer un nouvel utilisateur:</h2>
	{{ include ('users/_form.html.twig', {button: 'Créer'})}}
	</div>

{% endblock %}

templates/users/show.html.twig
{% extends 'base.html.twig' %}

{% block title users.nameUsers %}

{% block body %}
	<div class="jumbotron">
		<div class="container">
			<div class="row">
				<div class="col-md-8"></div>

				<div class="col-md-4">
					<h1>{{ users.nameUsers}}
						-
						{{users.firstnameUsers}}</h1>
					<div class="text-primary" style"font-size: 4rem;font-weight: bold;">{{users.phoneNumberUsers}}
					</div>
					<a href="#" class="btn btn-primary">
						Contactez l'utilisateur</a>
				</div>
			</div>
		</div>
	</div>

	<div class="container mt-4">

		<p>
			Bonjour
			{{users.firstnameUsers}}
		</p>

		<div class="row">
			<div class="col-md-6">
				<h2>Informations utilisateur</h2>
				<table class="table table-striped">
					<tr>
						<td>Nom</td>
						<td>{{users.nameUsers}}</td>
					</tr>
					<tr>
						<td>Prénom</td>
						<td>{{users.firstnameUsers}}</td>
					</tr>
					<tr>
						<td>Téléphone</td>
						<td>{{users.phoneNumberUsers}}</td>
					</tr>
					<tr>
						<td>mail</td>
						<td>{{users.mail}}</td>
					</tr>
				</table>
			</div>
			<div class="col-md-4">
				<h2>Droit administrateur</h2>
			</div>
		</div>
	</div>
{% endblock %}